apiVersion: v1
kind: Service
metadata:
  name: {{ include "genieacs.fullname" . }}
  labels:
    {{- include "genieacs.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- if or .Values.genieacs.service.annotations .Values.genieacs.service.loadBalancerIP }}
  annotations:
    {{- with .Values.genieacs.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.genieacs.service.loadBalancerIP }}
    # MetalLB annotation for fixed IP
    metallb.universe.tf/loadBalancerIPs: {{ .Values.genieacs.service.loadBalancerIP }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.genieacs.service.type }}
  {{- if and (eq .Values.genieacs.service.type "LoadBalancer") .Values.genieacs.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.genieacs.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.genieacs.service.ports.cwmp }}
      targetPort: cwmp
      protocol: TCP
      name: cwmp
    - port: {{ .Values.genieacs.service.ports.nbi }}
      {{- if .Values.nbiAuth.enabled }}
      targetPort: nbi-auth
      {{- else }}
      targetPort: nbi
      {{- end }}
      protocol: TCP
      name: nbi
    - port: {{ .Values.genieacs.service.ports.fs }}
      targetPort: fs
      protocol: TCP
      name: fs
    - port: {{ .Values.genieacs.service.ports.ui }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "genieacs.selectorLabels" . | nindent 4 }}