{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genieacs.fullname" . }}-secret
  labels:
    {{- include "genieacs.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  GENIEACS_UI_JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
{{- end }}