apiVersion: v2
name: genieacs-nbi-auth
description: A Helm chart for GenieACS with NBI API Key Authentication
type: application
version: 0.2.0
appVersion: "1.2.13"
keywords:
  - genieacs
  - tr-069
  - cwmp
  - acs
  - network-management
  - nbi-auth
home: https://genieacs.com
sources:
  - https://github.com/genieacs/genieacs
maintainers:
  - name: Sumitro Aji Prabowo