{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genieacs.mongodb.name" . }}-secret
  labels:
    {{- include "genieacs.mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}
{{- end }}