apiVersion: v1
kind: Secret
metadata:
  name: genieacs-secret
  namespace: genieacs
  labels:
    app.kubernetes.io/name: genieacs
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  # IMPORTANT: Change this value before deployment!
  # Generate with: openssl rand -hex 32
  GENIEACS_UI_JWT_SECRET: "7d41ad7108a519f72bc94eebf655edb07f95d9383cb308e529211b49febaeea3"