apiVersion: v1
kind: Secret
metadata:
  name: genieacs-secret
  namespace: genieacs
  labels:
    app.kubernetes.io/name: genieacs
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  # IMPORTANT: Change this value before deployment!
  # Generate with: openssl rand -hex 32
  GENIEACS_UI_JWT_SECRET: "changeme-generate-with-openssl-rand-hex-32"
